[workspace]
members = ["vessel_type", "python_bindings"]
[workspace.package]
version = "0.3.0"
edition = "2024"

[package]
name = "autowsgr_native"
version.workspace = true
edition.workspace = true


[build-dependencies]
vessel_type = { path = "./vessel_type" }
strum = "0.28"
image = "0.25"

[dependencies]
vessel_type = { path = "./vessel_type" }

[dev-dependencies]
image = "0.25"
walkdir = "2.3.2"
