[package]
name = "image-autowsgrs-py"
version = "0.1.0"
edition = "2024"

[lib]
name = "image_autowsgrs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28", features = ["extension-module", "abi3-py312"] }
numpy = "0.28"
image-autowsgrs = { path = ".." }
vessel-type = { path = "../vessel-type", features = ["pyo3"] }
